--- #YAML:1.0
name:               Plack-Session-Store-Redis
version:            0.03
abstract:           Redis based session store for Plack apps.
author:
    - Lee Aylward <leedo@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    JSON:            0
    Plack:           0
    Plack::Session:  0
    Redis:           0
    Test::More:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
